name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Debug: Show app.js before replacement'
        run: |
          echo "--- app.js content before replacement ---"
          cat app.js
          echo "-----------------------------------------"

      - name: Replace placeholders in app.js
        # This 'env' block makes the secrets available as environment variables
        # for the commands in the 'run' step, which is a more robust method.
        env:
          API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          SHARED_PASSWORD: ${{ secrets.SHARED_PASSWORD }}
        run: |
          sed -i "s|__API_KEY__|$API_KEY|g" app.js
          sed -i "s|__AUTH_DOMAIN__|$AUTH_DOMAIN|g" app.js
          sed -i "s|__PROJECT_ID__|$PROJECT_ID|g" app.js
          sed -i "s|__STORAGE_BUCKET__|$STORAGE_BUCKET|g" app.js
          sed -i "s|__MESSAGING_SENDER_ID__|$MESSAGING_SENDER_ID|g" app.js
          sed -i "s|__APP_ID__|$APP_ID|g" app.js
          sed -i "s|__SHARED_PASSWORD__|$SHARED_PASSWORD|g" app.js

      - name: 'Debug: Show app.js after replacement'
        run: |
          echo "--- app.js content after replacement ---"
          cat app.js
          echo "----------------------------------------"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
